COMMON_SOURCES = display.c open.c control.c menu.c playlist.c modules.c preferences.c gtk_callbacks.c

gtk_SOURCES = gtk.c gtk_interface.c gtk_support.c $(COMMON_SOURCES)
gnome_SOURCES = gnome.c gnome_interface.c gnome_support.c $(COMMON_SOURCES)
