# Extract plugins and convenience libraries from the libtool libraries
# being built, excluding the ones using them.

PLUGINS = $(VLC_PLUGINS:%=lib%.la)
PARTIAL_PLUGINS = $(PLUGINS:_plugin.la=_plugin.partial.la)

.PRECIOUS: $(PARTIAL_PLUGINS) $(PLUGINS:.la=.la.symbollist) $(PARTIAL_PLUGINS:=.symbollist) \
	$(PARTIAL_PLUGINS:%.partial.la=.deps/%.partial.la.o)

# Given the list of symbols from the original plugin, and the original
# plugin itself with its libtool archive, we'll build the actual partial
# plugin _object_. At this step, we also need to fetch the static
# dependencies from the source plugin since we'll actually merge them
# into the object. The -Wl,-u flag forces the linker to pull the entry
# symbol from the archive, replacing the former module_expose.c approach.
#
# NOTE: After this step, the partial plugin object exists but it's not
#       yet wrapped in a libtool archive the rest of the project can
#       use.
.deps/%_plugin.partial.la.o: %_plugin.la %_plugin.la.symbollist
	$(AM_V_at)$(MKDIR_P) $(@D)
	$(AM_V_at)$(AM_V_P) && set -x; \
	libpath=`grep old_library= "$<" | cut -d"'" -f 2`; \
	vlc_entrypoint=`$(NM) ".libs/$${libpath}" | \
		awk '$$2 == "T" && $$3 ~ /^_?vlc_entry__[A-Za-z0-9_]+$$/ { print $$3; exit }'`; \
	static_dependencies=`$(top_srcdir)/buildsystem/dependencies.sh static $<`; \
	$(CXX) $(CXXFLAGS) $(LDFLAGS) \
		-r -o $@ -fPIC \
		-Wl,-u,$${vlc_entrypoint} \
		".libs/$${libpath}" \
		$${static_dependencies}
	@# Localize ALL symbols except VLC entry points
	$(AM_V_at)$(OBJCOPY) --wildcard \
		-G 'vlc_entry*' \
		$@ || rm -f $@
# Unfortunately libtool checks that the following comment is there to check that
# libtool object is correct, so provide it
	$(AM_V_at)echo "# .deps/$*_plugin.partial.la.lo - a libtool object file" > $*_plugin.partial.la.lo
	$(AM_V_at)echo "# Generated by doltcompile, not libtool" >> $*_plugin.partial.la.lo
	$(AM_V_at)echo "non_pic_object=none" >> $*_plugin.partial.la.lo
	$(AM_V_at)echo "pic_object=$(abs_builddir)/$@" >> $*_plugin.partial.la.lo

# Generate a libtool archive the built partially linked object
# constructed from the source plugin and its dependencies. At this
# point, we also need to provide the dependencies that we could not or
# didn't want to link.
%_plugin.partial.la: %_plugin.la %_plugin.la.symbollist .deps/%_plugin.partial.la.o
	$(AM_V_at)$(LIBTOOL) $(AM_V_lt) --mode=link --tag=CXX c++ -Wl,-Ur -fPIC -o $@ "$@.lo" \
		-export-symbols-regex "^vlc_entry__"
	$(AM_V_GEN)dependencies=`$(top_srcdir)/buildsystem/dependencies.sh forward $<`; \
	frameworks=`echo "$($*_plugin_la_LDFLAGS)" \
		| grep -oE '\-(framework|weak_framework),[A-Za-z][A-Za-z0-9_]*' \
		| sort -u \
		| sed 's/^/-Wl,/' \
		| tr '\n' ' '`; \
	sed -i.orig "s,dependency_libs=.*\$$,dependency_libs=' $${dependencies}'," $@ \
		|| (rm $@ && exit 1); \
	sed -i.orig "s|inherited_linker_flags='\(.*\)'|inherited_linker_flags='\1 $${frameworks}'|" $@ \
		|| (rm $@ && exit 1); \
	echo "" >> $@;


if HAVE_PARTIAL_LINKING
CLEANFILES += \
	$(PLUGINS:=.symbollist) \
	$(PARTIAL_PLUGINS) \
	$(PARTIAL_PLUGINS:%.partial.la=.deps/%.partial.la.o)
endif
