COMMON_SOURCES = imdct_common.c

imdct_SOURCES = imdct.c imdct_c.c srfft_c.c $(COMMON_SOURCES)
imdctsse_SOURCES = imdct.c imdct_sse.c srfft_sse.c $(COMMON_SOURCES)
imdct3dn_SOURCES = imdct.c imdct_3dn.c srfft_3dn.c $(COMMON_SOURCES)
