      $CONFIG \
      --without-contrib \
      --enable-nls \
      --enable-shared-libvlc \
      --enable-update-check \
      --enable-lua \
      --enable-faad \
      --enable-flac \
      --enable-theora \
      --enable-twolame \
      --enable-quicktime \
      --enable-real \
      --enable-realrtsp \
      --enable-ffmpeg --with-ffmpeg-mp3lame --with-ffmpeg-faac \
      --with-ffmpeg-config-path=/usr/win32/bin --with-ffmpeg-zlib \
      --enable-live555 --with-live555-tree=/usr/win32/live.com \
      --enable-dca \
      --enable-libass \
      --enable-x264 \
      --disable-zvbi --enable-telx \
      --enable-dvdread --with-dvdnav-config-path=/usr/win32/bin \
      --enable-shout \
      --enable-goom \
      --enable-caca --with-caca-config-path=/usr/win32/bin \
      --enable-portaudio \
      --enable-sdl --with-sdl-config-path=/usr/win32/bin \
      --enable-qt4 \
      --enable-wxwidgets --with-wx-config-path=/usr/win32/lib/wx/config \
      --with-freetype-config-path=/usr/win32/bin \
      --with-fribidi-config-path=/usr/win32/bin \
      --with-xml2-config-path=/usr/win32/bin \
      --enable-mozilla --with-mozilla-sdk-path=/usr/win32/gecko-sdk \
      --enable-activex \
      --disable-gnomevfs --disable-hal --disable-gtk \
      --disable-cddax --disable-vcdx \
      --disable-libcddb --disable-dvb --disable-zvbi \
      --disable-pulse
