/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_callbacks.h"
#include "gtk_interface.h"
#include "gtk_support.h"

GtkWidget*
create_intf_window (void)
{
  GtkWidget *intf_window;
  GtkWidget *vbox2;
  GtkWidget *handlebox2;
  GtkWidget *menubar1;
  guint tmp_key;
  GtkWidget *menubar_file;
  GtkWidget *menubar_file_menu;
  GtkAccelGroup *menubar_file_menu_accels;
  GtkWidget *menubar_open;
  GtkWidget *menubar_disc;
  GtkWidget *separator4;
  GtkWidget *menubar_exit;
  GtkWidget *menubar_view;
  GtkWidget *menubar_view_menu;
  GtkAccelGroup *menubar_view_menu_accels;
  GtkWidget *menubar_title;
  GtkWidget *menubar_chapter;
  GtkWidget *separator11;
  GtkWidget *menubar_playlist;
  GtkWidget *menubar_modules;
  GtkWidget *menubar_settings;
  GtkWidget *menubar_settings_menu;
  GtkAccelGroup *menubar_settings_menu_accels;
  GtkWidget *separator7;
  GtkWidget *menubar_audio;
  GtkWidget *menubar_subpictures;
  GtkWidget *separator8;
  GtkWidget *menubar_preferences;
  GtkWidget *menubar_help;
  GtkWidget *menubar_help_menu;
  GtkAccelGroup *menubar_help_menu_accels;
  GtkWidget *menubar_about;
  GtkWidget *handlebox1;
  GtkWidget *toolbar;
  GtkWidget *toolbar_open;
  GtkWidget *toolbar_disc;
  GtkWidget *toolbar_back;
  GtkWidget *toolbar_stop;
  GtkWidget *toolbar_play;
  GtkWidget *toolbar_pause;
  GtkWidget *toolbar_slow;
  GtkWidget *toolbar_fast;
  GtkWidget *toolbar_playlist;
  GtkWidget *toolbar_prev;
  GtkWidget *toolbar_next;
  GtkWidget *entry1;
  GtkWidget *label6;
  GtkWidget *hscale;
  GtkWidget *label13;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  intf_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (intf_window), "intf_window", intf_window);
  gtk_window_set_title (GTK_WINDOW (intf_window), _("VideoLAN Client"));

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (intf_window), vbox2);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_ref (handlebox2);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "handlebox2", handlebox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox2), handlebox2, FALSE, TRUE, 0);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_container_add (GTK_CONTAINER (handlebox2), menubar1);

  menubar_file = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_file)->child),
                                   _("_File"));
  gtk_widget_add_accelerator (menubar_file, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (menubar_file);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_file", menubar_file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_file);
  gtk_container_add (GTK_CONTAINER (menubar1), menubar_file);

  menubar_file_menu = gtk_menu_new ();
  gtk_widget_ref (menubar_file_menu);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_file_menu", menubar_file_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menubar_file), menubar_file_menu);
  menubar_file_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (menubar_file_menu));

  menubar_open = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_open)->child),
                                   _("_Open File..."));
  gtk_widget_add_accelerator (menubar_open, "activate_item", menubar_file_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (menubar_open);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_open", menubar_open,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_open);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), menubar_open);
  gtk_tooltips_set_tip (tooltips, menubar_open, _("Open a File"), NULL);
  gtk_widget_add_accelerator (menubar_open, "activate", accel_group,
                              GDK_F3, 0,
                              GTK_ACCEL_VISIBLE);

  menubar_disc = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_disc)->child),
                                   _("Open _Disc..."));
  gtk_widget_add_accelerator (menubar_disc, "activate_item", menubar_file_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (menubar_disc);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_disc", menubar_disc,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_disc);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), menubar_disc);
  gtk_tooltips_set_tip (tooltips, menubar_disc, _("Open a DVD or VCD"), NULL);

  separator4 = gtk_menu_item_new ();
  gtk_widget_ref (separator4);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "separator4", separator4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator4);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), separator4);
  gtk_widget_set_sensitive (separator4, FALSE);

  menubar_exit = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_exit)->child),
                                   _("E_xit"));
  gtk_widget_add_accelerator (menubar_exit, "activate_item", menubar_file_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (menubar_exit);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_exit", menubar_exit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_exit);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), menubar_exit);
  gtk_tooltips_set_tip (tooltips, menubar_exit, _("Exit the program"), NULL);
  gtk_widget_add_accelerator (menubar_exit, "activate", accel_group,
                              GDK_Q, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  menubar_view = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_view)->child),
                                   _("_View"));
  gtk_widget_add_accelerator (menubar_view, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (menubar_view);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_view", menubar_view,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_view);
  gtk_container_add (GTK_CONTAINER (menubar1), menubar_view);

  menubar_view_menu = gtk_menu_new ();
  gtk_widget_ref (menubar_view_menu);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_view_menu", menubar_view_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menubar_view), menubar_view_menu);
  menubar_view_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (menubar_view_menu));

  menubar_title = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_title)->child),
                                   _("_Title"));
  gtk_widget_add_accelerator (menubar_title, "activate_item", menubar_view_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (menubar_title);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_title", menubar_title,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_title);
  gtk_container_add (GTK_CONTAINER (menubar_view_menu), menubar_title);
  gtk_widget_set_sensitive (menubar_title, FALSE);
  gtk_tooltips_set_tip (tooltips, menubar_title, _("Navigate through the stream"), NULL);

  menubar_chapter = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_chapter)->child),
                                   _("_Chapter"));
  gtk_widget_add_accelerator (menubar_chapter, "activate_item", menubar_view_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (menubar_chapter);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_chapter", menubar_chapter,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_chapter);
  gtk_container_add (GTK_CONTAINER (menubar_view_menu), menubar_chapter);
  gtk_widget_set_sensitive (menubar_chapter, FALSE);

  separator11 = gtk_menu_item_new ();
  gtk_widget_ref (separator11);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "separator11", separator11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator11);
  gtk_container_add (GTK_CONTAINER (menubar_view_menu), separator11);
  gtk_widget_set_sensitive (separator11, FALSE);

  menubar_playlist = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_playlist)->child),
                                   _("_Playlist..."));
  gtk_widget_add_accelerator (menubar_playlist, "activate_item", menubar_view_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (menubar_playlist);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_playlist", menubar_playlist,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_playlist);
  gtk_container_add (GTK_CONTAINER (menubar_view_menu), menubar_playlist);
  gtk_tooltips_set_tip (tooltips, menubar_playlist, _("Open the playlist window"), NULL);

  menubar_modules = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_modules)->child),
                                   _("_Modules..."));
  gtk_widget_add_accelerator (menubar_modules, "activate_item", menubar_view_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (menubar_modules);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_modules", menubar_modules,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_modules);
  gtk_container_add (GTK_CONTAINER (menubar_view_menu), menubar_modules);
  gtk_widget_set_sensitive (menubar_modules, FALSE);
  gtk_tooltips_set_tip (tooltips, menubar_modules, _("Open the plugin manager"), NULL);

  menubar_settings = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_settings)->child),
                                   _("_Settings"));
  gtk_widget_add_accelerator (menubar_settings, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (menubar_settings);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_settings", menubar_settings,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_settings);
  gtk_container_add (GTK_CONTAINER (menubar1), menubar_settings);

  menubar_settings_menu = gtk_menu_new ();
  gtk_widget_ref (menubar_settings_menu);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_settings_menu", menubar_settings_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menubar_settings), menubar_settings_menu);
  menubar_settings_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (menubar_settings_menu));

  separator7 = gtk_menu_item_new ();
  gtk_widget_ref (separator7);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "separator7", separator7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator7);
  gtk_container_add (GTK_CONTAINER (menubar_settings_menu), separator7);
  gtk_widget_set_sensitive (separator7, FALSE);

  menubar_audio = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_audio)->child),
                                   _("A_udio"));
  gtk_widget_add_accelerator (menubar_audio, "activate_item", menubar_settings_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (menubar_audio);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_audio", menubar_audio,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_audio);
  gtk_container_add (GTK_CONTAINER (menubar_settings_menu), menubar_audio);
  gtk_widget_set_sensitive (menubar_audio, FALSE);
  gtk_tooltips_set_tip (tooltips, menubar_audio, _("Select audio language"), NULL);

  menubar_subpictures = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_subpictures)->child),
                                   _("Sub _Pictures"));
  gtk_widget_add_accelerator (menubar_subpictures, "activate_item", menubar_settings_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (menubar_subpictures);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_subpictures", menubar_subpictures,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_subpictures);
  gtk_container_add (GTK_CONTAINER (menubar_settings_menu), menubar_subpictures);
  gtk_widget_set_sensitive (menubar_subpictures, FALSE);
  gtk_tooltips_set_tip (tooltips, menubar_subpictures, _("Select sub-title"), NULL);

  separator8 = gtk_menu_item_new ();
  gtk_widget_ref (separator8);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "separator8", separator8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator8);
  gtk_container_add (GTK_CONTAINER (menubar_settings_menu), separator8);
  gtk_widget_set_sensitive (separator8, FALSE);

  menubar_preferences = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_preferences)->child),
                                   _("_Preferences..."));
  gtk_widget_add_accelerator (menubar_preferences, "activate_item", menubar_settings_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (menubar_preferences);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_preferences", menubar_preferences,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_preferences);
  gtk_container_add (GTK_CONTAINER (menubar_settings_menu), menubar_preferences);
  gtk_widget_set_sensitive (menubar_preferences, FALSE);
  gtk_tooltips_set_tip (tooltips, menubar_preferences, _("Configure the application"), NULL);

  menubar_help = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_help)->child),
                                   _("_Help"));
  gtk_widget_add_accelerator (menubar_help, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (menubar_help);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_help", menubar_help,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_help);
  gtk_container_add (GTK_CONTAINER (menubar1), menubar_help);

  menubar_help_menu = gtk_menu_new ();
  gtk_widget_ref (menubar_help_menu);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_help_menu", menubar_help_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menubar_help), menubar_help_menu);
  menubar_help_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (menubar_help_menu));

  menubar_about = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (menubar_about)->child),
                                   _("_About..."));
  gtk_widget_add_accelerator (menubar_about, "activate_item", menubar_help_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (menubar_about);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "menubar_about", menubar_about,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar_about);
  gtk_container_add (GTK_CONTAINER (menubar_help_menu), menubar_about);
  gtk_tooltips_set_tip (tooltips, menubar_about, _("About this application"), NULL);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_ref (handlebox1);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "handlebox1", handlebox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox2), handlebox1, FALSE, TRUE, 0);

  toolbar = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
  gtk_widget_ref (toolbar);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "toolbar", toolbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar);
  gtk_container_add (GTK_CONTAINER (handlebox1), toolbar);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar), 1);
  gtk_toolbar_set_space_size (GTK_TOOLBAR (toolbar), 16);
  gtk_toolbar_set_space_style (GTK_TOOLBAR (toolbar), GTK_TOOLBAR_SPACE_LINE);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (toolbar), GTK_RELIEF_NONE);

  toolbar_open = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Open"),
                                _("Open a File"), NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (toolbar_open);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "toolbar_open", toolbar_open,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_open);

  toolbar_disc = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Disc"),
                                _("Open a DVD or VCD"), NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (toolbar_disc);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "toolbar_disc", toolbar_disc,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_disc);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar));

  toolbar_back = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Back"),
                                _("Go Backwards"), NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (toolbar_back);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "toolbar_back", toolbar_back,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_back);
  gtk_widget_set_sensitive (toolbar_back, FALSE);

  toolbar_stop = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Stop"),
                                _("Stop Stream"), NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (toolbar_stop);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "toolbar_stop", toolbar_stop,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_stop);
  gtk_widget_set_sensitive (toolbar_stop, FALSE);

  toolbar_play = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Play"),
                                _("Play Stream"), NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (toolbar_play);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "toolbar_play", toolbar_play,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_play);

  toolbar_pause = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Pause"),
                                _("Pause Stream"), NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (toolbar_pause);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "toolbar_pause", toolbar_pause,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_pause);

  toolbar_slow = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Slow"),
                                _("Play Slower"), NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (toolbar_slow);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "toolbar_slow", toolbar_slow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_slow);

  toolbar_fast = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Fast"),
                                _("Play Faster"), NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (toolbar_fast);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "toolbar_fast", toolbar_fast,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_fast);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar));

  toolbar_playlist = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Playlist"),
                                _("Open Playlist"), NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (toolbar_playlist);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "toolbar_playlist", toolbar_playlist,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_playlist);

  toolbar_prev = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Prev"),
                                _("Previous File"), NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (toolbar_prev);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "toolbar_prev", toolbar_prev,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_prev);

  toolbar_next = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Next"),
                                _("Next File"), NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (toolbar_next);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "toolbar_next", toolbar_next,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_next);

  entry1 = gtk_entry_new ();
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (vbox2), entry1, FALSE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (entry1), _("Tired of boring stub messages ? Write your own exciting message here !!"));

  label6 = gtk_label_new (_("This part of the interface doesn't work yet. You can drag the slider below, though:"));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (vbox2), label6, FALSE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label6), 5, 0);

  hscale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 100, 1, 6.25, 0)));
  gtk_widget_ref (hscale);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "hscale", hscale,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hscale);
  gtk_box_pack_start (GTK_BOX (vbox2), hscale, FALSE, TRUE, 0);
  gtk_scale_set_value_pos (GTK_SCALE (hscale), GTK_POS_BOTTOM);
  gtk_range_set_update_policy (GTK_RANGE (hscale), GTK_UPDATE_DELAYED);

  label13 = gtk_label_new (_("HEY ! YOU CAN DROP A FILE ON VLC TOO :-)"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (vbox2), label13, FALSE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label13), 0, 5);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_ref (statusbar1);
  gtk_object_set_data_full (GTK_OBJECT (intf_window), "statusbar1", statusbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar1);
  gtk_box_pack_end (GTK_BOX (vbox2), statusbar1, FALSE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (intf_window), "drag_data_received",
                      GTK_SIGNAL_FUNC (on_intf_window_drag_data_received),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (intf_window), "delete_event",
                      GTK_SIGNAL_FUNC (on_intf_window_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (menubar_open), "activate",
                      GTK_SIGNAL_FUNC (on_menubar_open_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (menubar_disc), "activate",
                      GTK_SIGNAL_FUNC (on_menubar_disc_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (menubar_exit), "activate",
                      GTK_SIGNAL_FUNC (on_menubar_exit_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (menubar_playlist), "activate",
                      GTK_SIGNAL_FUNC (on_menubar_playlist_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (menubar_modules), "activate",
                      GTK_SIGNAL_FUNC (on_menubar_modules_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (menubar_preferences), "activate",
                      GTK_SIGNAL_FUNC (on_menubar_preferences_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (menubar_about), "activate",
                      GTK_SIGNAL_FUNC (on_menubar_about_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_open), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_open_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_disc), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_disc_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_back), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_back_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_stop), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_stop_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_play), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_play_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_pause), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_pause_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_slow), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_slow_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_fast), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_fast_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_playlist), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_playlist_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_prev), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_prev_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_next), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_next_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (hscale), "button_release_event",
                      GTK_SIGNAL_FUNC (on_hscale_button_release_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (hscale), "button_press_event",
                      GTK_SIGNAL_FUNC (on_hscale_button_press_event),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (intf_window), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (intf_window), accel_group);

  return intf_window;
}

GtkWidget*
create_intf_popup (void)
{
  GtkWidget *intf_popup;
  GtkAccelGroup *intf_popup_accels;
  guint tmp_key;
  GtkWidget *popup_play;
  GtkWidget *popup_pause;
  GtkWidget *popup_slow;
  GtkWidget *popup_fast;
  GtkWidget *separator6;
  GtkWidget *popup_open;
  GtkWidget *popup_disc;
  GtkWidget *separator5;
  GtkWidget *popup_navigation;
  GtkWidget *separator10;
  GtkWidget *popup_audio;
  GtkWidget *popup_subpictures;
  GtkWidget *separator9;
  GtkWidget *main_window_toggle;
  GtkWidget *popup_about;
  GtkWidget *popup_exit;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  intf_popup = gtk_menu_new ();
  gtk_object_set_data (GTK_OBJECT (intf_popup), "intf_popup", intf_popup);
  intf_popup_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (intf_popup));

  popup_play = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (popup_play)->child),
                                   _("_Play"));
  gtk_widget_add_accelerator (popup_play, "activate_item", intf_popup_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (popup_play);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "popup_play", popup_play,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (popup_play);
  gtk_container_add (GTK_CONTAINER (intf_popup), popup_play);

  popup_pause = gtk_menu_item_new_with_label (_("Pause"));
  gtk_widget_ref (popup_pause);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "popup_pause", popup_pause,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (popup_pause);
  gtk_container_add (GTK_CONTAINER (intf_popup), popup_pause);

  popup_slow = gtk_menu_item_new_with_label (_("Slow"));
  gtk_widget_ref (popup_slow);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "popup_slow", popup_slow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (popup_slow);
  gtk_container_add (GTK_CONTAINER (intf_popup), popup_slow);

  popup_fast = gtk_menu_item_new_with_label (_("Fast"));
  gtk_widget_ref (popup_fast);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "popup_fast", popup_fast,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (popup_fast);
  gtk_container_add (GTK_CONTAINER (intf_popup), popup_fast);

  separator6 = gtk_menu_item_new ();
  gtk_widget_ref (separator6);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "separator6", separator6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator6);
  gtk_container_add (GTK_CONTAINER (intf_popup), separator6);
  gtk_widget_set_sensitive (separator6, FALSE);

  popup_open = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (popup_open)->child),
                                   _("_Open File..."));
  gtk_widget_add_accelerator (popup_open, "activate_item", intf_popup_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (popup_open);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "popup_open", popup_open,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (popup_open);
  gtk_container_add (GTK_CONTAINER (intf_popup), popup_open);
  gtk_tooltips_set_tip (tooltips, popup_open, _("Open a File"), NULL);

  popup_disc = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (popup_disc)->child),
                                   _("Open _Disc..."));
  gtk_widget_add_accelerator (popup_disc, "activate_item", intf_popup_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (popup_disc);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "popup_disc", popup_disc,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (popup_disc);
  gtk_container_add (GTK_CONTAINER (intf_popup), popup_disc);
  gtk_tooltips_set_tip (tooltips, popup_disc, _("Open a DVD or VCD"), NULL);

  separator5 = gtk_menu_item_new ();
  gtk_widget_ref (separator5);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "separator5", separator5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator5);
  gtk_container_add (GTK_CONTAINER (intf_popup), separator5);
  gtk_widget_set_sensitive (separator5, FALSE);

  popup_navigation = gtk_menu_item_new_with_label (_("Navigation"));
  gtk_widget_ref (popup_navigation);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "popup_navigation", popup_navigation,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (popup_navigation);
  gtk_container_add (GTK_CONTAINER (intf_popup), popup_navigation);
  gtk_widget_set_sensitive (popup_navigation, FALSE);

  separator10 = gtk_menu_item_new ();
  gtk_widget_ref (separator10);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "separator10", separator10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator10);
  gtk_container_add (GTK_CONTAINER (intf_popup), separator10);
  gtk_widget_set_sensitive (separator10, FALSE);

  popup_audio = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (popup_audio)->child),
                                   _("A_udio"));
  gtk_widget_add_accelerator (popup_audio, "activate_item", intf_popup_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (popup_audio);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "popup_audio", popup_audio,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (popup_audio);
  gtk_container_add (GTK_CONTAINER (intf_popup), popup_audio);
  gtk_widget_set_sensitive (popup_audio, FALSE);

  popup_subpictures = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (popup_subpictures)->child),
                                   _("Sub _Pictures"));
  gtk_widget_add_accelerator (popup_subpictures, "activate_item", intf_popup_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (popup_subpictures);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "popup_subpictures", popup_subpictures,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (popup_subpictures);
  gtk_container_add (GTK_CONTAINER (intf_popup), popup_subpictures);
  gtk_widget_set_sensitive (popup_subpictures, FALSE);

  separator9 = gtk_menu_item_new ();
  gtk_widget_ref (separator9);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "separator9", separator9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator9);
  gtk_container_add (GTK_CONTAINER (intf_popup), separator9);
  gtk_widget_set_sensitive (separator9, FALSE);

  main_window_toggle = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (main_window_toggle)->child),
                                   _("show/hide main _window"));
  gtk_widget_add_accelerator (main_window_toggle, "activate_item", intf_popup_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (main_window_toggle);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "main_window_toggle", main_window_toggle,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_window_toggle);
  gtk_container_add (GTK_CONTAINER (intf_popup), main_window_toggle);

  popup_about = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (popup_about)->child),
                                   _("_About..."));
  gtk_widget_add_accelerator (popup_about, "activate_item", intf_popup_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (popup_about);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "popup_about", popup_about,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (popup_about);
  gtk_container_add (GTK_CONTAINER (intf_popup), popup_about);

  popup_exit = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (popup_exit)->child),
                                   _("E_xit"));
  gtk_widget_add_accelerator (popup_exit, "activate_item", intf_popup_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (popup_exit);
  gtk_object_set_data_full (GTK_OBJECT (intf_popup), "popup_exit", popup_exit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (popup_exit);
  gtk_container_add (GTK_CONTAINER (intf_popup), popup_exit);

  gtk_signal_connect (GTK_OBJECT (popup_play), "activate",
                      GTK_SIGNAL_FUNC (on_popup_play_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (popup_pause), "activate",
                      GTK_SIGNAL_FUNC (on_popup_pause_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (popup_slow), "activate",
                      GTK_SIGNAL_FUNC (on_popup_slow_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (popup_fast), "activate",
                      GTK_SIGNAL_FUNC (on_popup_fast_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (popup_open), "activate",
                      GTK_SIGNAL_FUNC (on_popup_open_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (popup_disc), "activate",
                      GTK_SIGNAL_FUNC (on_popup_disc_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (main_window_toggle), "activate",
                      GTK_SIGNAL_FUNC (on_main_window_toggle),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (popup_about), "activate",
                      GTK_SIGNAL_FUNC (on_popup_about_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (popup_exit), "activate",
                      GTK_SIGNAL_FUNC (on_popup_exit_activate),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (intf_popup), "tooltips", tooltips);

  return intf_popup;
}

GtkWidget*
create_intf_about (void)
{
  GtkWidget *intf_about;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox3;
  GtkWidget *label14;
  GtkWidget *label18;
  GtkWidget *frame1;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *dialog_action_area;
  GtkWidget *about_ok;

  intf_about = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (intf_about), "intf_about", intf_about);
  gtk_container_set_border_width (GTK_CONTAINER (intf_about), 5);
  gtk_window_set_title (GTK_WINDOW (intf_about), _("About"));
  gtk_window_set_position (GTK_WINDOW (intf_about), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (intf_about), FALSE, FALSE, FALSE);

  dialog_vbox1 = GTK_DIALOG (intf_about)->vbox;
  gtk_object_set_data (GTK_OBJECT (intf_about), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (intf_about), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox3, TRUE, TRUE, 0);

  label14 = gtk_label_new (_("VideoLAN Client"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (intf_about), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (vbox3), label14, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label14), 0, 10);

  label18 = gtk_label_new (_("(C) 1996, 1997, 1998, 1999, 2000, 2001 - the VideoLAN Team"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (intf_about), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (vbox3), label18, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label18), 0, 5);

  frame1 = gtk_frame_new (_("Authors"));
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (intf_about), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox3), frame1, FALSE, FALSE, 0);

  label16 = gtk_label_new (_("R\351gis Duchesne <regis@via.ecp.fr>\nMichel Lespinasse <walken@zoy.org>\nOlivier Pomel <pomel@via.ecp.fr>\nPierre Baillet <oct@zoy.org>\nJean-Philippe Grimaldi <jeanphi@via.ecp.fr>\nAndres Krapf <dae@via.ecp.fr>\nChristophe Massiot <massiot@via.ecp.fr>\nVincent Seguin <seguin@via.ecp.fr>\nBenoit Steiner <benny@via.ecp.fr>\nArnaud de Bossoreille de Ribou <bozo@via.ecp.fr>\nJean-Marc Dressler <polux@via.ecp.fr>\nGa\353l Hendryckx <jimmy@via.ecp.fr>\nSamuel Hocevar <sam@zoy.org>\nBrieuc Jeunhomme <bbp@via.ecp.fr>\nMichel Kaempf <maxx@via.ecp.fr>\nSt\351phane Borel <stef@via.ecp.fr>\nRenaud Dartus <reno@via.ecp.fr>\nHenri Fallon <henri@via.ecp.fr>"));
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (intf_about), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_container_add (GTK_CONTAINER (frame1), label16);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label16), 0.5, 0);
  gtk_misc_set_padding (GTK_MISC (label16), 5, 5);

  label17 = gtk_label_new (_("This is the VideoLAN client, a DVD and MPEG player. It can play MPEG and MPEG 2 files from a file or from a network source."));
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (intf_about), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (vbox3), label17, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label17), TRUE);
  gtk_misc_set_padding (GTK_MISC (label17), 0, 5);

  dialog_action_area = GTK_DIALOG (intf_about)->action_area;
  gtk_object_set_data (GTK_OBJECT (intf_about), "dialog_action_area", dialog_action_area);
  gtk_widget_show (dialog_action_area);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area), 10);

  about_ok = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (about_ok);
  gtk_object_set_data_full (GTK_OBJECT (intf_about), "about_ok", about_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about_ok);
  gtk_box_pack_start (GTK_BOX (dialog_action_area), about_ok, FALSE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (about_ok, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (about_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_about_ok_clicked),
                      NULL);

  gtk_widget_grab_default (about_ok);
  return intf_about;
}

GtkWidget*
create_intf_fileopen (void)
{
  GtkWidget *intf_fileopen;
  GtkWidget *fileopen_ok;
  GtkWidget *fileopen_cancel;

  intf_fileopen = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (intf_fileopen), "intf_fileopen", intf_fileopen);
  gtk_container_set_border_width (GTK_CONTAINER (intf_fileopen), 10);

  fileopen_ok = GTK_FILE_SELECTION (intf_fileopen)->ok_button;
  gtk_object_set_data (GTK_OBJECT (intf_fileopen), "fileopen_ok", fileopen_ok);
  gtk_widget_show (fileopen_ok);
  GTK_WIDGET_SET_FLAGS (fileopen_ok, GTK_CAN_DEFAULT);

  fileopen_cancel = GTK_FILE_SELECTION (intf_fileopen)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (intf_fileopen), "fileopen_cancel", fileopen_cancel);
  gtk_widget_show (fileopen_cancel);
  GTK_WIDGET_SET_FLAGS (fileopen_cancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (intf_fileopen), "destroy",
                      GTK_SIGNAL_FUNC (on_intf_fileopen_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (fileopen_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_fileopen_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (fileopen_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_fileopen_cancel_clicked),
                      NULL);

  return intf_fileopen;
}

GtkWidget*
create_intf_disc (void)
{
  GtkWidget *intf_disc;
  GtkWidget *dialog_vbox2;
  GtkWidget *vbox4;
  GtkWidget *hbox3;
  GtkWidget *frame2;
  GtkWidget *vbox5;
  GSList *disc_group = NULL;
  GtkWidget *disc_dvd;
  GtkWidget *disc_vcd;
  GtkWidget *frame3;
  GtkWidget *table1;
  GtkObject *disc_title_adj;
  GtkWidget *disc_title;
  GtkObject *disc_chapter_adj;
  GtkWidget *disc_chapter;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *hbox2;
  GtkWidget *label19;
  GtkWidget *disc_name;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbox1;
  GtkWidget *disc_ok;
  GtkWidget *disc_cancel;

  intf_disc = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (intf_disc), "intf_disc", intf_disc);
  gtk_window_set_title (GTK_WINDOW (intf_disc), _("Open Disc"));
  gtk_window_set_policy (GTK_WINDOW (intf_disc), FALSE, FALSE, FALSE);

  dialog_vbox2 = GTK_DIALOG (intf_disc)->vbox;
  gtk_object_set_data (GTK_OBJECT (intf_disc), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_vbox2), 5);

  vbox4 = gtk_vbox_new (FALSE, 5);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), vbox4, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 5);

  hbox3 = gtk_hbox_new (FALSE, 5);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox3, TRUE, TRUE, 0);

  frame2 = gtk_frame_new (_("Disc type"));
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (hbox3), frame2, TRUE, TRUE, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (frame2), vbox5);

  disc_dvd = gtk_radio_button_new_with_label (disc_group, _("DVD"));
  disc_group = gtk_radio_button_group (GTK_RADIO_BUTTON (disc_dvd));
  gtk_widget_ref (disc_dvd);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "disc_dvd", disc_dvd,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (disc_dvd);
  gtk_box_pack_start (GTK_BOX (vbox5), disc_dvd, FALSE, FALSE, 0);

  disc_vcd = gtk_radio_button_new_with_label (disc_group, _("VCD"));
  disc_group = gtk_radio_button_group (GTK_RADIO_BUTTON (disc_vcd));
  gtk_widget_ref (disc_vcd);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "disc_vcd", disc_vcd,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (disc_vcd);
  gtk_box_pack_start (GTK_BOX (vbox5), disc_vcd, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (disc_vcd, FALSE);

  frame3 = gtk_frame_new (_("Starting position"));
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (hbox3), frame3, TRUE, TRUE, 0);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (frame3), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 5);

  disc_title_adj = gtk_adjustment_new (1, 1, 65536, 1, 10, 10);
  disc_title = gtk_spin_button_new (GTK_ADJUSTMENT (disc_title_adj), 1, 0);
  gtk_widget_ref (disc_title);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "disc_title", disc_title,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (disc_title);
  gtk_table_attach (GTK_TABLE (table1), disc_title, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  disc_chapter_adj = gtk_adjustment_new (1, 1, 65536, 1, 10, 10);
  disc_chapter = gtk_spin_button_new (GTK_ADJUSTMENT (disc_chapter_adj), 1, 0);
  gtk_widget_ref (disc_chapter);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "disc_chapter", disc_chapter,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (disc_chapter);
  gtk_table_attach (GTK_TABLE (table1), disc_chapter, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label20 = gtk_label_new (_("Chapter"));
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table1), label20, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label21 = gtk_label_new (_("Title"));
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table1), label21, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  hbox2 = gtk_hbox_new (FALSE, 5);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox2, TRUE, TRUE, 0);

  label19 = gtk_label_new (_("Device name"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox2), label19, FALSE, FALSE, 0);

  disc_name = gtk_entry_new ();
  gtk_widget_ref (disc_name);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "disc_name", disc_name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (disc_name);
  gtk_box_pack_start (GTK_BOX (hbox2), disc_name, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (disc_name), _("/dev/dvd"));

  dialog_action_area1 = GTK_DIALOG (intf_disc)->action_area;
  gtk_object_set_data (GTK_OBJECT (intf_disc), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 5);

  hbox1 = gtk_hbox_new (TRUE, 5);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_end (GTK_BOX (dialog_action_area1), hbox1, FALSE, TRUE, 0);

  disc_ok = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (disc_ok);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "disc_ok", disc_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (disc_ok);
  gtk_box_pack_start (GTK_BOX (hbox1), disc_ok, FALSE, TRUE, 0);

  disc_cancel = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (disc_cancel);
  gtk_object_set_data_full (GTK_OBJECT (intf_disc), "disc_cancel", disc_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (disc_cancel);
  gtk_box_pack_start (GTK_BOX (hbox1), disc_cancel, FALSE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (disc_dvd), "toggled",
                      GTK_SIGNAL_FUNC (on_disc_dvd_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (disc_vcd), "toggled",
                      GTK_SIGNAL_FUNC (on_disc_vcd_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (disc_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_disc_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (disc_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_disc_cancel_clicked),
                      NULL);

  return intf_disc;
}

GtkWidget*
create_intf_playlist (void)
{
  GtkWidget *intf_playlist;
  GtkWidget *vbox6;
  GtkWidget *menubar2;
  GtkWidget *add1;
  GtkWidget *delete1;
  GtkWidget *delete1_menu;
  GtkAccelGroup *delete1_menu_accels;
  guint tmp_key;
  GtkWidget *crop1;
  GtkWidget *invert1;
  GtkWidget *selection;
  GtkWidget *selection1;
  GtkWidget *scrolledwindow1;
  GtkWidget *clist1;
  GtkWidget *label22;
  GtkWidget *label23;

  intf_playlist = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (intf_playlist), "intf_playlist", intf_playlist);
  gtk_window_set_title (GTK_WINDOW (intf_playlist), _("Playlist"));
  gtk_window_set_default_size (GTK_WINDOW (intf_playlist), 386, 200);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (intf_playlist), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (intf_playlist), vbox6);

  menubar2 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar2);
  gtk_object_set_data_full (GTK_OBJECT (intf_playlist), "menubar2", menubar2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar2);
  gtk_box_pack_start (GTK_BOX (vbox6), menubar2, FALSE, FALSE, 0);

  add1 = gtk_menu_item_new_with_label (_("Add"));
  gtk_widget_ref (add1);
  gtk_object_set_data_full (GTK_OBJECT (intf_playlist), "add1", add1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (add1);
  gtk_container_add (GTK_CONTAINER (menubar2), add1);

  delete1 = gtk_menu_item_new_with_label (_("Delete"));
  gtk_widget_ref (delete1);
  gtk_object_set_data_full (GTK_OBJECT (intf_playlist), "delete1", delete1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (menubar2), delete1);

  delete1_menu = gtk_menu_new ();
  gtk_widget_ref (delete1_menu);
  gtk_object_set_data_full (GTK_OBJECT (intf_playlist), "delete1_menu", delete1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (delete1), delete1_menu);
  delete1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (delete1_menu));

  crop1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (crop1)->child),
                                   _("_crop"));
  gtk_widget_add_accelerator (crop1, "activate_item", delete1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (crop1);
  gtk_object_set_data_full (GTK_OBJECT (intf_playlist), "crop1", crop1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (crop1);
  gtk_container_add (GTK_CONTAINER (delete1_menu), crop1);

  invert1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (invert1)->child),
                                   _("_invert"));
  gtk_widget_add_accelerator (invert1, "activate_item", delete1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (invert1);
  gtk_object_set_data_full (GTK_OBJECT (intf_playlist), "invert1", invert1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (invert1);
  gtk_container_add (GTK_CONTAINER (delete1_menu), invert1);

  selection = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (selection)->child),
                                   _("_selection"));
  gtk_widget_add_accelerator (selection, "activate_item", delete1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (selection);
  gtk_object_set_data_full (GTK_OBJECT (intf_playlist), "selection", selection,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (selection);
  gtk_container_add (GTK_CONTAINER (delete1_menu), selection);

  selection1 = gtk_menu_item_new_with_label (_("Selection"));
  gtk_widget_ref (selection1);
  gtk_object_set_data_full (GTK_OBJECT (intf_playlist), "selection1", selection1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (selection1);
  gtk_container_add (GTK_CONTAINER (menubar2), selection1);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (intf_playlist), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox6), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist1 = gtk_clist_new (2);
  gtk_widget_ref (clist1);
  gtk_object_set_data_full (GTK_OBJECT (intf_playlist), "clist1", clist1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), clist1);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 257);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 80);
  gtk_clist_set_selection_mode (GTK_CLIST (clist1), GTK_SELECTION_EXTENDED);
  gtk_clist_column_titles_hide (GTK_CLIST (clist1));

  label22 = gtk_label_new (_("File"));
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (intf_playlist), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label22);

  label23 = gtk_label_new (_("Duration"));
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (intf_playlist), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, label23);

  gtk_signal_connect (GTK_OBJECT (intf_playlist), "delete_event",
                      GTK_SIGNAL_FUNC (on_intf_playlist_destroy_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (crop1), "activate",
                      GTK_SIGNAL_FUNC (on_crop_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (invert1), "activate",
                      GTK_SIGNAL_FUNC (on_invertselection_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (selection), "activate",
                      GTK_SIGNAL_FUNC (on_delete_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist1), "event",
                      GTK_SIGNAL_FUNC (on_clist1_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist1), "drag_data_received",
                      GTK_SIGNAL_FUNC (on_intf_playlist_drag_data_received),
                      NULL);

  return intf_playlist;
}

