/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRTextEntryDelegateProtocol.h"

@class BRAccount;

@interface BRAccountSelectorPasswordCollector : NSObject <BRTextEntryDelegate>
{
    BRAccount *_account;
}

- (id)initWithAccount:(id)fp8;
- (void)textDidChange:(id)fp8;
- (void)textDidEndEditing:(id)fp8;
- (void)dealloc;

@end

