/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRTextEntryDelegateProtocol.h"

@class BRAccountSelector, BRAccountType;

@interface BRAccountSelectorUserNameCollector : NSObject <BRTextEntryDelegate>
{
    BRAccountType *_type;
    BRAccountSelector *_accountSelector;
}

- (id)initWithType:(id)fp8 accountSelector:(id)fp12;
- (void)textDidChange:(id)fp8;
- (void)textDidEndEditing:(id)fp8;
- (void)dealloc;

@end

