/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRScrollableTextLayer.h>

@class BRTextLayer, NSTimer;

@interface BRAutoScrollingTextLayer : BRScrollableTextLayer
{
    BRTextLayer *_pursuitTextLayer;
    NSTimer *_scrollTimer;
    BOOL _scrolling;
}

- (id)init;
- (void)dealloc;
- (void)setAttributedString:(id)fp8;
- (struct CGRect)scrollableBounds;
- (void)_beginScroll:(id)fp8;
- (void)layoutSublayers;
- (float)maxScrollPosition;
- (void)startScrolling;
- (void)stopScrolling;
- (float)repeatInterval;

@end

