/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRAutoScrollingTextLayer.h>

@interface BRAutoScrollingTextLayer (Private)
- (void)animationDidStart:(id)fp8;
- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;
- (void)_resetScrollTimer;
- (void)_clearScrollTimer;
- (void)_createPursuitLayerIfNecessary;
@end

