/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class NSTimer;

@interface BRBackgroundTaskManager : BRSingleton
{
    int _numberOfCurrentBackgroundProcesses;
    double _lastUserActivity;
    NSTimer *_backgroundProcessSuppressionTimer;
}

+ (void)holdOffBackgroundTasks;
+ (BOOL)okToDoBackgroundProcessing;
+ (void)startingBackgroundProcessing;
+ (void)finishedBackgroundProcessing;
+ (void)startingMediaSyncing;
+ (void)finishedMediaSyncing;
+ (BOOL)mediaSyncInProgress;
+ (void)startedFileCopy:(id)fp8;
+ (void)finishedFileCopy:(id)fp8;
+ (BOOL)backgroundTasksRunning;
+ (double)timeSinceLastUserAction;
+ (id)singleton;
+ (void)setSingleton:(id)fp8;
- (id)init;
- (void)dealloc;

@end

