/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRBaseMediaAsset.h>

@class NSString;

@interface BRBackupPhotoAsset : BRBaseMediaAsset
{
    NSString *_artPath;
}

- (id)initWithPath:(id)fp8;
- (void)dealloc;
- (id)assetID;
- (BOOL)isLocal;
- (BOOL)hasCoverArt;
- (id)coverArt;
- (id)coverArtID;
- (id)mediaType;

@end

