/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayer.h>

@class NSAttributedString;

@interface BRCCTextLayer : BRLayer
{
    struct CGRect _CCDisplayFrame;
    NSAttributedString *_wholeAttributedString;
    struct CGPoint _attributedStringLocation;
    char *_characterPopulationArray;
    BOOL _isCompletelyErased;
}

- (id)init;
- (void)_createSublayers;
- (id)initWithAttributedString:(id)fp8 atLocation:(struct CGPoint)fp12 withCCDisplayFrame:(struct CGRect)fp20;
- (void)dealloc;
- (void)layoutSublayers;
- (id)attributedString;
- (struct CGPoint)stringLocation;
- (struct CGRect)CCDisplayFrame;
- (void)eraseCharactersAtLocation:(struct CGPoint)fp8 length:(int)fp16;
- (BOOL)isCompletelyErased;

@end

