/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRCharacterSelectionLayer.h>

@interface BRCharacterSelectionLayer (GlyphBuilding)
- (id)_loadPickableItems:(int)fp8;
- (id)_buildGlyphUIFromPickableItems:(id)fp8 includeSpace:(BOOL)fp12;
- (id)_buildBackArrow;
- (id)_buildSpaceLabel;
- (id)_buildDoneLabel;
- (id)_buildMoreLabel;
- (id)_buildDeleteLabel;
@end

