/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRCoverArtPreviewLayoutManager : NSObject
{
}

- (struct CGRect)frameFor:(id)fp8 inBounds:(struct CGRect)fp12;
- (void)layoutSublayersOfLayer:(id)fp8;

@end

