/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRMediaType, NSArray, NSDictionary, NSMutableArray, NSTimer;

@interface BRCoverArtPreviewControl : BRControl
{
    NSArray *_imageProviders;
    NSMutableArray *_availableImages;
    BRMediaType *_mediaType;
    NSDictionary *_layerActions;
    NSTimer *_crossfadeTimer;
    long _imageIndex;
    BOOL _artworkNeedsDeletterboxing;
}

- (id)init;
- (void)dealloc;
- (void)setImageProvider:(id)fp8;
- (void)setImageProviders:(id)fp8;
- (void)setAsset:(id)fp8;
- (void)setAssets:(id)fp8;
- (void)setMissingAssetType:(id)fp8;
- (void)controlWasActivated;
- (void)controlWillDeactivate;
- (void)controlWasDeactivated;
- (void)setDeletterboxAssetArtwork:(BOOL)fp8;

@end

