/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRCoverArtPreviewControl.h>

@interface BRCoverArtPreviewControl (Private)
- (void)_addImageFromMedia:(id)fp8 toCollection:(id)fp12;
- (void)_loadImage:(id)fp8;
- (void)_crossFadeToNextImage:(id)fp8;
- (void)_cleanupTimer;
- (void)_scheduleTimerOnMainThread;
- (void)_updateCoverArt:(id)fp8;
@end

