/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSLock, NSPredicate, NSSet, NSString;

@interface BRDataStore : NSObject
{
    NSLock *_dataLock;
    NSString *_entityName;
    NSPredicate *_predicate;
    NSSet *_mediaTypes;
    NSArray *_descriptors;
    NSArray *_cache;
    BOOL _cacheResults;
}

- (id)initWithEntityName:(id)fp8 predicate:(id)fp12 mediaTypes:(id)fp16;
- (id)initWithEntityName:(id)fp8 predicate:(id)fp12 mediaTypes:(id)fp16 shouldCacheResults:(BOOL)fp20;
- (void)dealloc;
- (void)setSortDescriptors:(id)fp8;
- (void)purge;
- (id)data;
- (id)dataReportingError:(id *)fp8;

@end

