/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRDiskArbHandler.h>

@interface BRDiskArbHandler (DiscHandling)
- (id)_mountedDisks;
- (id)_mountedDVDs;
- (id)_mountedCDs;
- (void)_findMountedDVDs;
- (void)_findMountedCDs;
- (void)_diskInserted:(id)fp8;
- (void)_diskEjected:(id)fp8;
@end

