/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRController.h>

#import "BRTextEntryDelegateProtocol.h"

@class BRHeaderControl, BRIPv4AddressEntryControl, BRTextControl, NSString;

@interface BRDottedQuadEntryController : BRController <BRTextEntryDelegate>
{
    id <BRDottedQuadEntryDelegate> _delegate;
    BRIPv4AddressEntryControl *_editor;
    BRTextControl *_prompt;
    BRHeaderControl *_header;
    NSString *_dottedQuad;
}

- (id)initWithTitle:(id)fp8 prompt:(id)fp12 label:(id)fp16 notifying:(id)fp20;
- (void)dealloc;
- (void)setFrame:(struct CGRect)fp8;
- (void)setIcon:(id)fp8 horizontalOffset:(float)fp12 kerningFactor:(float)fp16;
- (void)textDidChange:(id)fp8;
- (void)textDidEndEditing:(id)fp8;
- (id)dottedQuad;
- (void)setDottedQuad:(id)fp8;

@end

