/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayerController.h>

@class BRDVDMediaAsset, BRDVDPlayer, BRResumeMenuControl, BRTransportControl, NSDictionary, NSMutableDictionary, NSTimer;

@interface BRDVDPlayerController : BRMediaPlayerController
{
    BRDVDPlayer *_player;
    BRResumeMenuControl *_resumeMenu;
    BRTransportControl *_transport;
    NSDictionary *_committedCCLayers;
    NSMutableDictionary *_nextCCLayers;
    NSTimer *_suppressBackgroundProcessTimer;
    BRDVDMediaAsset *_dvdAsset;
    BOOL _lastActionWasMenuKeyPressed;
    BOOL _hasEjectMenu;
}

- (id)initWithAsset:(id)fp8;
- (void)dealloc;
- (void)willBePushed;
- (void)wasPushed;
- (void)wasPopped;
- (BOOL)brEventAction:(id)fp8;
- (id)player;

@end

