/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRBaseMediaAsset.h>

@class BRImage, NSString;

@interface BRDVDMediaAsset : BRBaseMediaAsset
{
    NSString *_pathToDVD;
    NSString *_pathToVideoFolder;
    NSString *_title;
    NSString *_identifier;
    BRImage *_coverArt;
}

+ (id)assetFromDiskInfo:(id)fp8;
+ (BOOL)isValidDVDFolder:(id)fp8 pathToVideoFolder:(id *)fp12;
- (id)initWithBRDiskInfo:(id)fp8;
- (id)initWithPath:(id)fp8;
- (void)dealloc;
- (id)assetID;
- (BOOL)hasCoverArt;
- (id)coverArt;
- (id)coverArtID;
- (id)title;
- (id)pathToVideoFolder;
- (id)identifier;

@end

