/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRVideoPlayer.h>

@interface BRDVDPlayer : BRVideoPlayer
{
}

- (void)setRenderer:(id)fp8;
- (BOOL)dvdLoadedAndVisible;
- (void)showDVDWindow;
- (void)hideDVDWindow;
- (id)curImage;
- (void)goToInitialPosition;
- (void)playFromCurrentPosition;
- (void)playFromBeginning;
- (BOOL)hasLastPlayedBookmark;
- (void)playFromLastPosition;
- (BOOL)hasDefaultBookmark;
- (void)playFromDefaultBookmark;
- (void)showDVDMenu;
- (BOOL)showingDVDMenu;
- (BOOL)handleMenuButtonClick;
- (BOOL)handlePlayPauseButtonClick;
- (BOOL)handleRightArrowClick;
- (BOOL)handleLeftArrowClick;
- (BOOL)handleUpArrowClick;
- (BOOL)handleDownArrowClick;

@end

