/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRAlertController.h>

@interface BRFatalExceptionAlertController : BRAlertController
{
}

+ (id)controllerForFatalException:(id)fp8;
+ (id)controllerForFatalNSException:(id)fp8;
- (BOOL)brEventAction:(id)fp8;

@end

