/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayer.h>

@interface BRFadeMaskLayer : BRLayer
{
    float _topFadeHeight;
    float _bottomFadeHeight;
    float _leftFadeWidth;
    float _rightFadeWidth;
    struct CGFunction *_shadingFunction;
}

- (id)init;
- (void)dealloc;
- (void)setTopFadeHeight:(float)fp8;
- (float)topFadeHeight;
- (void)setBottomFadeHeight:(float)fp8;
- (float)bottomFadeHeight;
- (void)setLeftFadeWidth:(float)fp8;
- (float)leftFadeWidth;
- (void)setRightFadeWidth:(float)fp8;
- (float)rightFadeWidth;
- (void)drawInContext:(struct CGContext *)fp8;
- (void)setEnableMaskAnimation:(BOOL)fp8;

@end

