/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class BRLayer;

@interface BRGlyphCellContents : NSObject
{
    int _glyphType;
    BRLayer *_layer;
}

- (id)initWithLayer:(id)fp8 glyphType:(int)fp12;
- (void)dealloc;
- (id)layer;
- (int)glyphType;

@end

