/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayer.h>

@class BRImageLayer;

@interface BRHorizontalSegmentedWidget : BRLayer
{
    BRImageLayer *_leftEndLayer;
    BRImageLayer *_centerLayer;
    BRImageLayer *_rightEndLayer;
}

- (id)init;
- (void)dealloc;
- (void)setLeftFile:(id)fp8 centerFile:(id)fp12 rightFile:(id)fp16;
- (void)setLeftImage:(id)fp8 centerImage:(id)fp12 rightImage:(id)fp16;

@end

