/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRImageLoader.h>

@interface BRImageLoader (ImageLoading)
- (void)_updateArtwork:(id)fp8;
- (void)_abandonArtwork:(id)fp8;
@end

