/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRImageLayer.h>

@interface BRImageLayer (Deprecated)
- (void)setImage:(id)fp8 downsampleTo:(struct CGSize)fp12;
@end

