/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRPanel.h>

@class BRImageControl, BRSyncProgressControl;

@interface BRImageAndSyncingPreviewController : BRPanel
{
    BRImageControl *_imageControl;
    BRSyncProgressControl *_syncProgressControl;
    BOOL _hasProgress;
}

- (id)init;
- (void)dealloc;
- (void)setImage:(id)fp8 downsampleTo:(struct CGSize)fp12;
- (void)setImage:(id)fp8;
- (id)imageControl;
- (void)controlWillActivate;
- (void)setHasSyncProgress:(BOOL)fp8;
- (void)setReflectionOffset:(float)fp8;
- (void)setReflectionAmount:(float)fp8;

@end

