/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayer.h>

@class BRImage;

@interface BRImageLayer : BRLayer
{
    BRImage *_image;
    struct CGSize _lastDownsample;
    BOOL _autoDownsample;
}

- (void)dealloc;
- (void)setImage:(id)fp8;
- (id)image;
- (struct CGSize)pixelBounds;
- (float)aspectRatio;
- (void)setAutomaticDownsample:(BOOL)fp8;
- (BOOL)automaticDownsample;
- (void)layoutSublayers;

@end

