/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSString;

@interface BRIPConfiguration : NSObject
{
    NSString *_wirelessNetwork;
    NSString *_wirelessMACAddress;
    NSString *_wirelessIPAddress;
    NSString *_wirelessSubnetMask;
    NSString *_wirelessRouter;
    NSArray *_wirelessDNSAddresses;
    long _wirelessSignalQuality;
    unsigned int _wirelessUseDHCP:1;
    unsigned int _wirelessActive:1;
    NSString *_wiredMACAddress;
    NSString *_wiredIPAddress;
    NSString *_wiredSubnetMask;
    NSString *_wiredRouter;
    NSArray *_wiredDNSAddresses;
    unsigned int _wiredUseDHCP:1;
    unsigned int _wiredActive:1;
}

+ (void)startMonitoringNetworkChanges:(BOOL)fp8;
- (id)initFromCurrentConfiguration;
- (void)dealloc;
- (id)description;
- (void)setUseDHCPForInterface:(int)fp8;
- (void)setAddress:(id)fp8 subnetMask:(id)fp12 router:(id)fp16 forInterface:(int)fp20;
- (void)setDNSAddresses:(id)fp8 forInterface:(int)fp12;
- (BOOL)isActiveForInterface:(int)fp8;
- (BOOL)useDHCPForInterface:(int)fp8;
- (id)MACaddressForInterface:(int)fp8;
- (id)IPaddressForInterface:(int)fp8;
- (id)subnetMaskForInterface:(int)fp8;
- (id)routerForInterface:(int)fp8;
- (id)dnsAddressesForInterface:(int)fp8;
- (id)wirelessNetwork;
- (long)wirelessSignalQuality;

@end

