/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRTextWithSpinnerController.h>

@class BRIPhotoShareListener;

@interface BRIPhotoShareDiscoveryDialog : BRTextWithSpinnerController
{
    BRIPhotoShareListener *_listener;
}

- (id)init;
- (void)dealloc;
- (void)controlWasActivated;
- (void)controlWillDeactivate;

@end

