/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRIPv4AddressSelectionLayer.h>

@interface BRIPv4AddressSelectionLayer (Building)
- (id)_buildOctetBackgroundLayers;
- (id)_buildDigitLayers;
- (id)_buildDotLayers;
- (id)_buildArrowsLayer;
- (id)_buildDoneLayer;
@end

