/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayer.h>

@class BRScrollingItemLayer, BRSelectionLozengeLayer;

@interface BRListLayer : BRLayer
{
    BRLayer *_widgetBackingLayer;
    BRSelectionLozengeLayer *_widget;
    BRScrollingItemLayer *_list;
    BOOL _widgetHidden;
}

- (id)init;
- (void)dealloc;
- (void)setDatasource:(id)fp8;
- (id)datasource;
- (void)setSelectedRow:(long)fp8;
- (long)selectedRow;
- (void)refill;
- (float)listHeightToMaximum:(float)fp8;
- (void)setLastItemCentered:(BOOL)fp8;
- (BOOL)lastItemCentered;
- (void)setSelectionWidgetHidden:(BOOL)fp8;
- (BOOL)selectionWidgetIsHidden;
- (void)setShowsWidgetBackingLayer:(BOOL)fp8;
- (BOOL)showsWidgetBackingLayer;
- (id)visibleRowsAndRange:(struct _NSRange *)fp8;
- (void)setAnimationMode:(int)fp8;
- (int)animationMode;
- (double)scrollDuration;
- (void)enterCurrentSelection;
- (void)leaveCurrentSelection;
- (void)layoutSublayers;

@end

