/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRListControl.h>

@interface BRListControl (SelectionHandling)
- (void)_delayedActivation:(id)fp8;
- (void)_leaveCurrentSelection;
- (void)_enterNewSelectionWithDelay:(BOOL)fp8;
@end

