/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRListControl.h>

@interface BRListControl (ScrollControl)
- (void)_scrollUp:(id)fp8;
- (void)_scrollDown:(id)fp8;
- (long)_backwardIndexForRowCount:(long)fp8 hitBoundary:(char *)fp12;
- (long)_forwardIndexForRowCount:(long)fp8 hitBoundary:(char *)fp12;
- (void)_setNewRow:(long)fp8;
- (void)_selectCurrentItem;
@end

