/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRMarchingIconLayer;

@interface BRMarchingIconControl : BRControl
{
    BRMarchingIconLayer *_march;
}

- (id)init;
- (void)dealloc;
- (void)setIconSource:(id)fp8;
- (id)iconSource;
- (void)reload;
- (void)setSelection:(long)fp8;
- (long)selection;
- (void)setFrontIconHidden:(BOOL)fp8;
- (BOOL)frontIconHidden;
- (id)selectedIcon;
- (id)selectedIconReflection;
- (id)layer;

@end

