/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRMediaParadeLayer, BRMediaParadeProvider;

@interface BRMediaParadeControl : BRControl
{
    BRMediaParadeLayer *_layer;
    BRMediaParadeProvider *_provider;
    BOOL _waitingForQueue;
    BOOL _pumpPrimed;
}

- (id)init;
- (void)dealloc;
- (id)layer;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)setImageProviders:(id)fp8;
- (void)setDeletterboxAssetArtwork:(BOOL)fp8;

@end

