/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class BRMediaHostEvent, BRMediaHostState, NSDictionary, NSMutableArray, NSSet, NSString, NSTimer;

@interface BRMediaHost : NSObject
{
    NSString *_hostID;
    NSDictionary *_hostInfo;
    NSMutableArray *_providers;
    int _hostType;
    NSMutableArray *_eventQueue;
    NSSet *_eventFilter;
    BRMediaHostEvent *_filterEvent;
    BRMediaHostState *_state;
    NSTimer *_eventTimer;
    BOOL _supportsPhotos;
}

+ (void)initialize;
+ (void)unmountAllHosts;
+ (id)mediaHost;
+ (id)syncingMediaHostWithHostInfo:(id)fp8;
+ (id)streamingMediaHostWithHostInfo:(id)fp8;
+ (id)daapMediaHostWithHostInfo:(id)fp8;
+ (id)currentHost;
+ (id)localHost;
+ (id)mediaHostMatchingHostInfo:(id)fp8;
+ (id)mediaHostForMediaProvider:(id)fp8;
+ (id)mediaHosts;
+ (id)syncingHost;
+ (id)streamingHosts;
+ (id)daapHosts;
+ (void)addMediaHost:(id)fp8;
+ (void)removeMediaHost:(id)fp8;
+ (void)removeMediaHost:(id)fp8 supressingRemoveNotification:(BOOL)fp12;
+ (BOOL)isPairedForSyncing:(char *)fp8;
+ (id)mountedMediaHosts;
+ (id)mediaProviderAdvertisingMediaTypes:(id)fp8;
+ (id)localMediaProviderAdvertisingMediaTypes:(id)fp8;
- (id)init;
- (void)dealloc;
- (void)setHostname:(id)fp8;
- (void)waitForEvent:(id)fp8 toProcessEvent:(id)fp12;
- (void)postEvent:(id)fp8;
- (void)abandonEvent:(id)fp8;
- (id)hostID;
- (id)hostInfo;
- (id)hostname;
- (void)_mount;
- (void)_unmount;
- (id)lastAccessedDate;
- (id)mediaProviders;
- (void)addMediaProvider:(id)fp8;
- (void)removeMediaProvider:(id)fp8;
- (void)removeMediaProviderWithID:(id)fp8 andMachineID:(id)fp12;
- (id)mediaProviderWithID:(id)fp8 andMachineID:(id)fp12;
- (id)mediaProviderAdvertisingMediaTypes:(id)fp8;
- (void)setState:(id)fp8;
- (id)state;
- (int)hostType;
- (BOOL)isLocal;
- (BOOL)supportsPhotos;
- (void)setSupportsPhotos:(BOOL)fp8;
- (BOOL)containsPasswordedProvider;

@end

