/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayerController.h>

@interface BRMediaPlayerController (CommandProcessing)
- (void)_playPauseAction:(id)fp8 withPlayer:(id)fp12;
- (void)_fastForwardAction:(id)fp8 withPlayer:(id)fp12;
- (void)_rewindAction:(id)fp8 withPlayer:(id)fp12;
@end

