/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@interface BRMetadataPopulatorFactory : BRSingleton
{
    id <BRMetadataPopulator> _tvShowPopulator;
    id <BRMetadataPopulator> _podcastPopulator;
    id <BRMetadataPopulator> _musicVideoPopulator;
    id <BRMetadataPopulator> _songPopulator;
    id <BRMetadataPopulator> _moviePopulator;
    id <BRMetadataPopulator> _movieTrailerPopulator;
    id <BRMetadataPopulator> _rssPopulator;
    id <BRMetadataPopulator> _audiobookPopulator;
    id <BRMetadataPopulator> _musicAlbumPopulator;
    id <BRMetadataPopulator> _ytPopulator;
}

+ (id)singleton;
+ (void)setSingleton:(id)fp8;
- (void)dealloc;
- (id)populatorForAsset:(id)fp8;

@end

