/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaHostConnectionDialog.h>

@interface BRMediaHostConnectionDialog (Private)
- (void)_checkMountStatus:(id)fp8;
- (void)_authRequired:(id)fp8;
- (void)_hostsChanged:(id)fp8;
@end

