/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMetadataLayer.h>

@interface BRMetadataLayer (Private)
- (void)_setTitle:(id)fp8;
- (void)_setRating:(id)fp8;
- (void)_setStarRating:(id)fp8;
- (void)_setSummary:(id)fp8;
- (void)_setMetadata:(id)fp8 withLabels:(id)fp12;
- (void)_setCopyright:(id)fp8;
@end

