/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayer.h>

@class BRTextLayer;

@interface BRMetadataLineLayer : BRLayer
{
    BRTextLayer *_labelLayer;
    BRTextLayer *_valueLayer;
    float _maxLabelWidth;
}

- (id)init;
- (void)dealloc;
- (void)setLabel:(id)fp8;
- (void)setValue:(id)fp8;
- (id)label;
- (id)value;
- (void)setMaxLabelWidth:(float)fp8;
- (void)layoutSublayers;

@end

