/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMetadataPreviewController.h>

@interface BRMetadataPreviewController (Metadata)
- (void)_showMetadataAfterDelay;
- (void)_updateMetadataLayer;
- (void)_coverArtChanged:(id)fp8;
- (void)_metadataTimerFired:(id)fp8;
@end

