/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRXMLMediaAsset.h>

@interface BRMovieTrailer : BRXMLMediaAsset
{
}

+ (id)movieTrailerFromMediaProvider:(id)fp8;
- (id)mediaType;

@end

