/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMusicNowPlayingControl.h>

@interface BRMusicNowPlayingControl (Updates)
- (void)_updateElapsedTime;
- (void)_updateTrackWithTransition:(BOOL)fp8;
- (id)_fetchCoverArt;
- (void)_updatePlayerShuffleState;
- (void)_updatePlayerRepeatState;
@end

