/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayer.h>

@class NSMutableDictionary, NSTimer;

@interface BRMusicNowPlayingLayer : BRLayer
{
    NSMutableDictionary *_currentTrackInfo;
    NSTimer *_flipRearrangeTimer;
    int _scheduledAnimationCount;
}

- (id)init;
- (void)dealloc;
- (id)createFrontLayer;
- (void)setCurrentTrackInfo:(id)fp8 WithTransition:(BOOL)fp12 TransitionDirection:(int)fp16 TransitionDuration:(float)fp20 NewTrackKicksInTime:(double)fp24 OldTrackFadeOutTime:(double)fp32;
- (void)updateTextStrings;
- (id)currentTrackInfo;
- (void)setElapsedTime:(double)fp8;
- (int)frontLayerSide;
- (void)setShuffleState:(BOOL)fp8;
- (void)setRepeatMode:(int)fp8;
- (void)setPlayerState:(int)fp8;
- (void)wasActivated;
- (void)performFlipAnimation:(float)fp8;
- (void)_reArrangeWhileFliping:(id)fp8;
- (void)_startScrolling;
- (void)enablePerspectiveTransform;
- (void)disablePerspectiveTransform;
- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;
- (void)removeAllPendingActions;

@end

