/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMusicTracklistMenuController.h>

@interface BRMusicTracklistMenuController (Private)
- (void)_playVideoTrack:(id)fp8;
- (void)_playerStateChanged:(id)fp8;
- (id)_cachedMDPreviewController;
- (id)_tracklist;
- (id)_trackAtIndex:(long)fp8;
- (long)_rowForTitle:(id)fp8;
@end

