/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class BRControllerStack, BRMusicPlayer, NSTimer;

@interface BRMusicNowPlayingMonitor : NSObject
{
    BRMusicPlayer *_player;
    BRControllerStack *_stack;
    int _state;
    NSTimer *_returnToNowPlaying;
}

- (id)init;
- (void)dealloc;
- (void)startMonitoringWithStack:(id)fp8;
- (void)stopMonitoring;

@end

