/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRMusicNowPlayingLayer, BRMusicPlayer, NSString, NSTimer;

@interface BRMusicNowPlayingControl : BRControl
{
    BRMusicNowPlayingLayer *_layer;
    BRMusicPlayer *_player;
    NSString *_lastAssetID;
    NSTimer *_flipTimer;
    NSTimer *_delayedContentUpdateTimer;
    NSTimer *_flipRearrangeTimer;
    NSTimer *_assetChangeAnimationUnblockTimer;
    double _flipDuration;
    double _flipInterval;
    double _assetChangeAnimationBlockTime;
    double _assetChangeAnimationDuration;
    double _newTrackKicksInTime;
    double _oldTrackFadeOutTime;
    double _postFlipAssetChangeAnimationBlockTime;
    int _transitionDirection;
    BOOL _assetChangeAnimationBlockFlag;
}

- (id)init;
- (void)dealloc;
- (id)layer;
- (void)controlWillActivate;
- (void)controlWasActivated;
- (void)controlWasDeactivated;

@end

