/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRMusicNowPlayingLayoutManager : NSObject
{
    float _coverArtRotation;
    float _coverArtSizeX;
    float _coverArtSizeY;
    float _stateIconWidth;
    float _textWidth;
    BOOL _shuffleState;
    BOOL _repeatState;
    struct CGPoint _randomOffset;
    struct CGPoint _coverArtPosition;
    struct CGPoint _trackNameTextPosition;
    struct CGPoint _artistNameTextPosition;
    struct CGPoint _albumNameTextPosition;
    struct CGPoint _trackXofXTextPosition;
    struct CGPoint _transportPosition;
    struct CGPoint _stateIconsLowerRightCornerPosition;
    float _coverArtReflectionAmount;
    struct CGSize _transportSize;
    BOOL _flip;
}

- (id)init;
- (void)dealloc;
- (void)updateRandomOffset;
- (void)layoutSublayersOfLayer:(id)fp8;
- (void)flipFrame:(struct CGRect *)fp8 parentFrame:(struct CGRect)fp12;
- (void)flipEverything;
- (void)setShuffleState:(BOOL)fp8;
- (void)setRepeatState:(BOOL)fp8;
- (int)frontLayerSide;

@end

