/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayer.h>

@class NSArray;

@interface BRMusicPlayer : BRMediaPlayer
{
    NSArray *_tracklist;
}

- (void)dealloc;
- (BOOL)interruptsSyncingWhenPlaying;
- (void)setMedia:(id)fp8 inTracklist:(id)fp12 error:(id *)fp16;
- (id)tracklist;
- (void)setShufflePlayback:(BOOL)fp8;
- (void)fadeOutVolume;
- (void)restoreVolume;
- (BOOL)shufflePlayback;
- (void)setRepeatMode:(int)fp8;
- (int)repeatMode;

@end

