/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRBaseMediaCollection.h>

@class BRMediaType, NSDictionary, NSMutableArray, NSString;

@interface BRMusicStoreCollection : BRBaseMediaCollection
{
    BRMediaType *_mediaType;
    NSDictionary *_dictionary;
    NSString *_collectionID;
    NSMutableArray *_childCollections;
    NSMutableArray *_mediaAssets;
    int _state;
}

+ (id)musicStoreCollectionFromProvider:(id)fp8 withDictionary:(id)fp12;
- (id)initWithMediaProvider:(id)fp8 dictionary:(id)fp12;
- (void)dealloc;
- (id)collectionID;
- (id)title;
- (id)childCollections;
- (id)mediaAssets;
- (id)mediaType;
- (id)childCollectionData;
- (id)mediaAssetsURL;
- (void)load;
- (void)unload;
- (BOOL)containsKindOfMediaType:(id)fp8;
- (id)childCollectionsWithKindOfMediaType:(id)fp8;
- (int)state;

@end

