/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRController.h>

#import "BRApplianceControllerIconProtocolProtocol.h"
#import "BRTextEntryDelegateProtocol.h"

@class BRHeaderControl, BRPasscodeEntryControl, BRTextControl, NSString;

@interface BRParentalControlsPasscodeController : BRController <BRTextEntryDelegate, BRApplianceControllerIconProtocol>
{
    BRController *_guardedController;
    BRPasscodeEntryControl *_editor;
    BRHeaderControl *_header;
    BRTextControl *_prompt;
    NSString *_passcodeToConfirm;
    int _mode;
}

- (id)initWithTitle:(id)fp8 prompt:(id)fp12 mode:(int)fp16 guarding:(id)fp20;
- (void)dealloc;
- (void)setFrame:(struct CGRect)fp8;
- (BOOL)isParentalControlsPasscodeRequired:(id *)fp8;
- (void)setPasscodeToConfirm:(id)fp8;
- (void)setIcon:(id)fp8 horizontalOffset:(float)fp12 kerningFactor:(float)fp16;
- (void)setApplianceIcon:(id)fp8;
- (void)setApplianceIconHidden:(BOOL)fp8;
- (struct CGRect)applianceIconFrame;
- (void)textDidChange:(id)fp8;
- (void)textDidEndEditing:(id)fp8;

@end

