/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImage, NSString;

@interface BRPairingPinControl : BRControl
{
    BRImage *_boxImage;
    NSString *_pin;
}

- (id)init;
- (void)dealloc;
- (void)setPIN:(id)fp8;
- (id)PIN;

@end

