/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRPasscodeSelectionLayer.h>

@interface BRPasscodeSelectionLayer (Framing)
- (float)_layoutUIWithHeight:(float)fp8;
- (struct CGRect)_selectionWidgetFrameForSelection:(int)fp8;
- (struct CGRect)_arrowsFrameForSelection:(int)fp8;
- (struct CGRect)_digitFrameForSelection:(int)fp8;
- (struct CGRect)_cellFrameForSelection:(int)fp8;
@end

