/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRPhotoController.h>

@interface BRPhotoController (BRPhotoControllerContent)
- (void)_setMediaHost:(id)fp8;
- (BOOL)_hasSettingsItem;
- (BOOL)_shouldShowSharedPhotosItem;
- (id)_currentItemList;
- (void)_updateMediaParadeSource;
- (void)_setItemList:(id)fp8;
- (id)_mediaListForCollection:(id)fp8 fromProvider:(id)fp12;
- (id)_grabPhotosForCollection:(id)fp8;
- (id)_buildSettingsMenu;
- (void)_handleSyncEvent;
- (void)_verifyCurrentCollection:(char *)fp8;
- (void)_coverArtUpdated:(id)fp8;
- (void)_scrollingWillStart:(id)fp8;
- (void)_scrollingWillStop:(id)fp8;
- (void)_scrollingSelectionChanged:(id)fp8;
@end

