/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaMenuController.h>

#import "BRMenuListItemProviderProtocol.h"

@class BRIconPreviewController, BRMediaParadeControl, NSArray;

@interface BRPhotoController : BRMediaMenuController <BRMenuListItemProvider>
{
    id <BRMediaCollection> _collection;
    id <BRMediaProvider><BRIPhotoMediaProvider> _provider;
    NSArray *_itemList;
    BRIconPreviewController *_noSyncedContentController;
    BRIconPreviewController *_staticPhotoIconController;
    BRMediaParadeControl *_photoPreviewController;
    int _maxRemotePhotosToLoad;
    BOOL _ignoreArtUpdateMessages;
    BOOL _hostIsLocal;
}

- (id)initWithError:(id *)fp8;
- (id)initWithHost:(id)fp8 error:(id *)fp12;
- (id)initWithProvider:(id)fp8 isLocal:(BOOL)fp12 error:(id *)fp16;
- (void)dealloc;
- (id)mediaProvider;
- (long)defaultIndex;
- (id)collection;
- (void)setCollection:(id)fp8 error:(id *)fp12;
- (void)itemSelected:(long)fp8;
- (id)itemForRow:(long)fp8;
- (long)itemCount;
- (id)titleForRow:(long)fp8;
- (float)heightForRow:(long)fp8;
- (BOOL)rowSelectable:(long)fp8;
- (void)wasExhumedByPoppingController:(id)fp8;
- (id)previewControlForItem:(long)fp8;
- (id)mediaPreviewMissingMediaType;

@end

