/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRPowerManager.h>

@interface BRPowerManager (Registrations)
- (void)_registerForSleepWake;
- (void)_registerForDisplayWake;
- (void)_registerForPowerSourceChanges;
- (void)_registerForPowerSettingChanges;
@end

