/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRPodcastMenuController.h>

@interface BRPodcastMenuController (Private)
- (id)_mediaProvider;
- (BOOL)_hasUnplayedShows:(id)fp8;
- (id)_displayNameForAsset:(id)fp8;
- (void)_cacheUnplayedTitles;
@end

