/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayer.h>

@interface BRProgressBarLayer : BRLayer
{
    double _maxValue;
    double _value;
    double _fillPercent;
}

- (id)init;
- (float)inset;
- (void)drawInContext:(struct CGContext *)fp8;
- (double)maxValue;
- (double)value;
- (void)setValue:(double)fp8 maxValue:(double)fp16;

@end

