/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRQTKitVideoPlayer.h>

@interface BRQTKitVideoPlayer (Chaptering)
- (void)_nextChapter;
- (void)_previousChapter;
- (double)_currentChapterMark;
- (double)_previousChapterMark;
- (double)_nextChapterMark;
- (void)_setVirtualChapterMark:(double)fp8;
- (double)_virtualChapterMark;
@end

