/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayer.h>

@interface BRReflectionLayer : BRLayer
{
    float _reflectionAmount;
    BOOL _flipped;
}

- (id)init;
- (void)setImage:(id)fp8;
- (void)setReflectionAmount:(float)fp8;
- (float)reflectionAmount;
- (void)setFlipped:(BOOL)fp8;
- (BOOL)flipped;

@end

