/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRRenderScene.h>

@interface BRRenderScene (SceneWindowPrivate)
- (void)_updateRootLayer;
- (void)reorderWindows;
- (void)moveToFront:(id)fp8;
- (void)removeWindow:(id)fp8;
- (void)updateLayerForWindow:(id)fp8;
@end

