/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRScrollingItemLayer.h>

@interface BRScrollingItemLayer (VisibleRange)
- (struct _NSRange)_visibleRangeFromRow:(long)fp8;
- (BOOL)_visibleRangeIsAtBottom:(struct _NSRange)fp8;
@end

