/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSentinel.h>

@interface BRSentinel (DatabaseSyncing)
- (void)_databaseUpdateStarted:(id)fp8;
- (void)_databaseUpdateComplete:(id)fp8;
- (void)_databaseObjectModified:(id)fp8;
- (void)_syncHostAvailabilityChanged:(id)fp8;
@end

