/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayer.h>

@class BRImage;

@interface BRSelectionLozengeLayer : BRLayer
{
    BRImage *_topImage;
    BRImage *_topCornerImage;
    BRImage *_edgeImage;
    BRImage *_bottomCornerImage;
    BRImage *_bottomImage;
}

+ (id)defaultActionForKey:(id)fp8;
- (id)init;
- (void)dealloc;
- (float)overHeightFactor;
- (float)topGlowHeight;
- (float)bottomGlowHeight;
- (float)edgeGlowWidth;
- (float)strokeHeight;
- (void)drawInContext:(struct CGContext *)fp8;

@end

