/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class BRControllerStack;

@interface BRSentinel : BRSingleton
{
    id <BRMusicStoreImageDecryptionAgent> _musicStoreImageDecryptionAgent;
    id <BRDRMSyncAgent> _drmSyncAgent;
    id <BRSyncProgressAgent> _syncProgressAgent;
    id <BRYTSigningAgent> _signingAgent;
    BRControllerStack *_controllerStack;
    unsigned int _networkDependentControllerCount;
    BOOL _shouldAttemptDRMSync;
}

+ (id)singleton;
+ (void)setSingleton:(id)fp8;
- (id)init;
- (void)dealloc;
- (void)setMusicStoreImageDecryptionAgent:(id)fp8;
- (id)musicStoreImageDecryptionAgent;
- (void)setCurrentControllerStack:(id)fp8;
- (void)networkDependentControllerWillBePushed;
- (void)networkDependentControllerWasPopped;
- (void)setDRMSyncAgent:(id)fp8;
- (id)drmSyncAgent;
- (void)setSyncProgressAgent:(id)fp8;
- (id)syncProgressAgent;
- (void)setYTSigningAgent:(id)fp8;
- (id)YTSigningAgent;
- (void)setShouldAttemptDRMSync:(BOOL)fp8;
- (BOOL)shouldAttemptDRMSync;

@end

