/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSegmentedSortLayer.h>

@interface BRSegmentedSortLayer (Private)
- (id)_leftEndCapTexureForSelectedState:(BOOL)fp8;
- (id)_rightEndCapTexureForSelectedState:(BOOL)fp8;
- (id)_dividerTextureForSelectedState:(BOOL)fp8;
- (id)_contentBackgroundTextureForSelectedState:(BOOL)fp8;
- (id)_attributedTextForSegment:(int)fp8 forSelectedState:(BOOL)fp12;
- (id)_loadImageFromFile:(id)fp8;
- (void)_updateSegmentState;
@end

