/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRSyncingMediaHost.h>

@class NSDate;

@interface BRStreamingMediaHost : BRSyncingMediaHost
{
    NSDate *_lastAccessedDate;
}

+ (id)streamingMediaHostWithHostInfo:(id)fp8;
- (id)init;
- (id)initWithCoder:(id)fp8;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (void)_mount;
- (id)lastAccessedDate;

@end

