/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaHost.h>

#import "NSCodingProtocol.h"

@interface BRSyncingMediaHost : BRMediaHost <NSCoding>
{
    int _version;
}

+ (id)syncingMediaHostWithHostInfo:(id)fp8;
- (id)init;
- (id)initWithHostInfo:(id)fp8;
- (int)_codingVersion;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)hostname;
- (void)setState:(id)fp8;

@end

