/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRController.h>

@class BRTextControl, BRWaitSpinnerControl;

@interface BRTextWithSpinnerController : BRController
{
    BRWaitSpinnerControl *_spinner;
    BRTextControl *_prompt;
    BOOL _isNetworkDependent;
}

- (id)initWithTitle:(id)fp8 text:(id)fp12;
- (id)initWithTitle:(id)fp8 text:(id)fp12 isNetworkDependent:(BOOL)fp16;
- (void)dealloc;
- (void)controlWasActivated;
- (BOOL)isNetworkDependent;
- (void)setIcon:(id)fp8 horizontalOffset:(float)fp12 kerningFactor:(float)fp16;

@end

