/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRThemeInfo.h>

@interface BRThemeInfo (AttributeCaching)
- (id)_cacheAttributes:(id)fp8 withName:(id)fp12;
- (id)_cacheLeftAlignedAttributesWithFont:(struct __CTFont *)fp8 color:(struct CGColor *)fp12 name:(id)fp16;
@end

