/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface BRTimer : NSObject
{
    NSString *_name;
    double _interval;
}

+ (id)createTimerWithName:(id)fp8;
- (id)initWithName:(id)fp8;
- (void)dealloc;

@end

