/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayer.h>

@class BRImageLayer, NSArray;

@interface BRTrackInfoLayer : BRLayer
{
    BRLayer *_background;
    BRImageLayer *_art;
    NSArray *_lines;
    float _maxLength;
    long _maxLines;
}

- (id)init;
- (void)dealloc;
- (void)setLines:(id)fp8 withImage:(id)fp12;
- (void)setImage:(id)fp8;
- (void)setMaxLines:(long)fp8;
- (void)layoutSublayers;

@end

