/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRTVShowsSingleShowController.h>

@interface BRTVShowsSingleShowController (Private)
- (long)_rowForTitle:(id)fp8;
- (id)_episodes;
- (void)_setEpisodes:(id)fp8;
- (id)_episodeAtIndex:(long)fp8;
- (id)_mediaProvider;
- (id)_controllerForSingleEpisode:(id)fp8;
@end

