/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRTVShowsController.h>

@interface BRTVShowsController (TVShowRows)
- (long)_rowForTitle:(id)fp8;
- (long)_tvShowIndexForMenuIndex:(long)fp8;
- (id)_buildMenuItemFromAsset:(id)fp8;
- (id)_buildMenuItemForMediaAsset:(id)fp8;
- (id)_buildMenuItemForMediaCollection:(id)fp8;
@end

