/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRVideo.h>

@interface BRVideo (MovieCreation)
- (BOOL)_createMovieWithAttributes:(id)fp8 error:(id *)fp12;
- (void)_updateContextSizeHint;
- (BOOL)_updateTrackInfoWithError:(id *)fp8;
@end

