/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayerController.h>

@class BRClosedCaptionControl, BRImage, BRResumeMenuControl, BRTransportControl, BRVideoPlayer, BRVideoPlayerHostLayer, BRVolumeControl, NSTimer;

@interface BRVideoPlayerController : BRMediaPlayerController
{
    BRVideoPlayer *_player;
    BRVideoPlayerHostLayer *_host;
    NSTimer *_fadeDelay;
    BRClosedCaptionControl *_closedCaptionControl;
    BRResumeMenuControl *_resumeMenu;
    BRTransportControl *_transport;
    BRVolumeControl *_volumeControl;
    NSTimer *_suppressBackgroundProcessTimer;
    id <BRVideoPlayerDelegate> _delegate;
    BRImage *_backupImage;
    float _backupImageHeight;
    BOOL _allowsResume;
    BOOL _drmSyncAttempted;
    BOOL _transportInhibited;
    BOOL _playbackInitiated;
}

- (id)init;
- (void)dealloc;
- (void)setVideoPlayer:(id)fp8;
- (id)videoPlayer;
- (id)player;
- (void)setAllowsResume:(BOOL)fp8;
- (BOOL)allowsResume;
- (void)setTransportControlInhibited:(BOOL)fp8;
- (BOOL)transportControlInhibited;
- (void)controlWillActivate;
- (void)controlWillDeactivate;
- (void)controlWasDeactivated;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setBackupImage:(id)fp8 withHeight:(float)fp12;
- (id)blurredVideoFrame;

@end

