/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRVideoStandardLoadMonitor.h>

@interface BRVideoStandardLoadMonitor (LoadStateMachine)
- (void)_updateLoadState:(long)fp8;
- (void)_startPlayback;
@end

