/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BackRow/BRLayer.h>

@class NSArray;

@interface BRWaitSpinnerLayer : BRLayer
{
    NSArray *_spinnerImages;
    BOOL _spins;
}

- (id)init;
- (void)dealloc;
- (void)setSpins:(BOOL)fp8;
- (BOOL)spins;
- (struct CGSize)preferredSize;

@end

