/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSDictionary.h"

@interface NSDictionary (BRDictionaryAdditions)
+ (id)dictionaryWithContentsOfURL:(id)fp8 withHeaderDictionary:(id)fp12;
+ (id)dictionaryWithContentsOfURL:(id)fp8 withHeaderDictionary:(id)fp12 cachePolicy:(unsigned int)fp16;
@end

