/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSFileManager.h"

@interface NSFileManager (BRFileSystemUtilities)
- (id)resolveAliasesInPath:(id)fp8;
- (BOOL)createDirectoryPath:(id)fp8 attributes:(id)fp12;
- (BOOL)purgeDirectoryAtPath:(id)fp8;
@end

