float32tos16_SOURCES = float32tos16.c
float32tos8_SOURCES = float32tos8.c
float32tou16_SOURCES = float32tou16.c
float32tou8_SOURCES = float32tou8.c
a52tospdif_SOURCES = a52tospdif.c
fixed32tos16_SOURCES = fixed32tos16.c
fixed32tofloat32_SOURCES = fixed32tofloat32.c
s16tofloat32_SOURCES = s16tofloat32.c
