# subsdelay
vlc_modules += {
    'name' : 'subsdelay',
    'sources' : files('subsdelay.c'),
    'plugin_dir' : 'spu',
}

# audiobargraph_v
vlc_modules += {
    'name' : 'audiobargraph_v',
    'sources' : files('audiobargraph_v.c'),
    'dependencies' : [m_lib],
    'shortname' : 'abg_v',
    'plugin_dir' : 'spu',
}

# logo
vlc_modules += {
    'name' : 'logo',
    'sources' : files('logo.c'),
    'plugin_dir' : 'spu',
}

# marq
vlc_modules += {
    'name' : 'marq',
    'sources' : files('marq.c'),
    'plugin_dir' : 'spu',
}

# mosaic
vlc_modules += {
    'name' : 'mosaic',
    'sources' : files('mosaic.c'),
    'dependencies' : [m_lib],
    'plugin_dir' : 'spu',
}

# rss
vlc_modules += {
    'name' : 'rss',
    'sources' : files('rss.c'),
    'plugin_dir' : 'spu',
}

# dynamicoverlay
vlc_modules += {
    'name' : 'dynamicoverlay',
    'sources' : files(
        'dynamicoverlay/dynamicoverlay_buffer.c',
        'dynamicoverlay/dynamicoverlay_queue.c',
        'dynamicoverlay/dynamicoverlay_commands.c',
        'dynamicoverlay/dynamicoverlay.c'
    ),
    'plugin_dir' : 'spu',
}
