chroma_i420_rgb_SOURCES = i420_rgb.c i420_rgb8.c i420_rgb16.c
chroma_i420_rgb_mmx_SOURCES = i420_rgb.c i420_rgb16.c
chroma_i420_yuy2_SOURCES = i420_yuy2.c
chroma_i420_yuy2_mmx_SOURCES = i420_yuy2.c
chroma_i422_yuy2_SOURCES = i422_yuy2.c
chroma_i422_yuy2_mmx_SOURCES = i422_yuy2.c
