.TH LIBVLC 1 "8 August 2002" Version 0.5.0
.SH NAME
vlc-config - script to get information about the installed version of libvlc
.SH SYNOPSIS
.B vlc-config
[\-\-prefix\fI[=DIR]\fP] [\-\-exec\-prefix\fI[=DIR]\fP] [\-\-version] [\-\-libs] [\-\-cflags]
.SH DESCRIPTION
.PP
\fIvlc-config\fP is a tool that is used to configure to determine
the compiler and linker flags that should be used to compile
and link programs that use \fIlibvlc\fP.
.
.SH OPTIONS
\fIvlc-config\fP accepts the following options:
.TP 8
.B  \-\-version
Print the currently installed version of \fIlibvlc\fP on the standard output.
.TP 8
.B  \-\-libs
Print the linker flags that are necessary to link a \fIlibvlc\fP program.
.TP 8
.B  \-\-cflags
Print the compiler flags that are necessary to compile a \fIlibvlc\fP program.
.TP 8
.B  \-\-prefix=PREFIX
If specified, use PREFIX instead of the installation prefix that \fIlibvlc\fP
was built with when computing the output for the \-\-cflags and
\-\-libs options. This option is also used for the exec prefix
if \-\-exec\-prefix was not specified. This option must be specified
before any \-\-libs or \-\-cflags options.
.TP 8
.B  \-\-exec\-prefix=PREFIX
If specified, use PREFIX instead of the installation exec prefix that
\fIlibvlc\fP was built with when computing the output for the \-\-cflags
and \-\-libs options.  This option must be specified before any
\-\-libs or \-\-cflags options.
.SH SEE ALSO
.BR vlc (1),
.SH COPYRIGHT
Copyright \(co  2002 Owen Taylor, modified by Sam Hocevar

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation.
