/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_videolan_jvlc_Audio */

#ifndef _Included_org_videolan_jvlc_Audio
#define _Included_org_videolan_jvlc_Audio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_videolan_jvlc_Audio
 * Method:    _getTrack
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_videolan_jvlc_Audio__1getTrack
  (JNIEnv *, jobject);

/*
 * Class:     org_videolan_jvlc_Audio
 * Method:    _setTrack
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_Audio__1setTrack
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_videolan_jvlc_Audio
 * Method:    _getChannel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_videolan_jvlc_Audio__1getChannel
  (JNIEnv *, jobject);

/*
 * Class:     org_videolan_jvlc_Audio
 * Method:    _setChannel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_Audio__1setChannel
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_videolan_jvlc_Audio
 * Method:    _getMute
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_videolan_jvlc_Audio__1getMute
  (JNIEnv *, jobject);

/*
 * Class:     org_videolan_jvlc_Audio
 * Method:    _setMute
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_Audio__1setMute
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_videolan_jvlc_Audio
 * Method:    _toggleMute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_Audio__1toggleMute
  (JNIEnv *, jobject);

/*
 * Class:     org_videolan_jvlc_Audio
 * Method:    _getVolume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_videolan_jvlc_Audio__1getVolume
  (JNIEnv *, jobject);

/*
 * Class:     org_videolan_jvlc_Audio
 * Method:    _setVolume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_Audio__1setVolume
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
