/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_videolan_jvlc_InputIntf */

#ifndef _Included_org_videolan_jvlc_InputIntf
#define _Included_org_videolan_jvlc_InputIntf
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
