/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_videolan_jvlc_JVLC */

#ifndef _Included_org_videolan_jvlc_JVLC
#define _Included_org_videolan_jvlc_JVLC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_videolan_jvlc_JVLC
 * Method:    createInstance
 * Signature: ([Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_videolan_jvlc_JVLC_createInstance
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_videolan_jvlc_JVLC
 * Method:    _destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_JVLC__1destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
