/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_videolan_jvlc_VLM */

#ifndef _Included_org_videolan_jvlc_VLM
#define _Included_org_videolan_jvlc_VLM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _addBroadcast
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_VLM__1addBroadcast
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray, jboolean, jboolean);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _deleteMedia
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_VLM__1deleteMedia
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _setEnabled
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_VLM__1setEnabled
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _setOutput
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_VLM__1setOutput
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _setInput
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_VLM__1setInput
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _setLoop
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_VLM__1setLoop
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _changeMedia
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_VLM__1changeMedia
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray, jboolean, jboolean);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _playMedia
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_VLM__1playMedia
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _stopMedia
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_VLM__1stopMedia
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _pauseMedia
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_VLM__1pauseMedia
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _seekMedia
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_org_videolan_jvlc_VLM__1seekMedia
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _showMedia
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_videolan_jvlc_VLM__1showMedia
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _getMediaposition
 * Signature: (Ljava/lang/String;I)F
 */
JNIEXPORT jfloat JNICALL Java_org_videolan_jvlc_VLM__1getMediaposition
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _getMediatime
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_jvlc_VLM__1getMediatime
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _getMedialength
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_jvlc_VLM__1getMedialength
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _getMediarate
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_jvlc_VLM__1getMediarate
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _getMediatitle
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_jvlc_VLM__1getMediatitle
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _getMediachapter
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_jvlc_VLM__1getMediachapter
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_videolan_jvlc_VLM
 * Method:    _getMediaseekable
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_videolan_jvlc_VLM__1getMediaseekable
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
