#! /bin/sh
# Copyright © 2008 Rémi Denis-Courmont

cd "$(dirname "$0")" || exit $?

# Look for configure #defines in public headers.
# There are incorrect, as external users don't have our <config.h>.
regexp="$(cat ../config.h.in | \
	sed -n -e 's/^#undef \([A-Z0-9_]*\)$/\1/p' | \
	grep -v 'WORDS_BIGENDIAN' | \
	xargs | \
	sed -e 's/ /\\\|/g')"

echo Looking for private defines in public headers...
! grep -- "$regexp" "$@" || exit $?
echo "None found."
