#! /bin/sh
# Plugin API consistency check for VLC
# Copyright © 2007 Rémi Denis-Courmont.

if ! diff -u libvlc-headers.sym libvlc-sorted.sym; then
	echo "Mismatching symbols found!"
	exit 1
fi

# TODO: we should pass this:
#if grep -e "^_" libvlc-headers.sym; then
#	echo "Illegal symbol name (starting with underscore) found!";
#	exit 1
#fi
