#! /bin/sh
# Plugin API consistency check for VLC
# Copyright © 2007 Rémi Denis-Courmont.

rm -f libvlc-headers.sym

cat ${srcdir}/../include/vlc_*.h | \
sed -n -e 's/^VLC_EXPORT\s*([^,]*,\s*\([a-zA-Z0-9_]*\)\s*,.*$/\1/p' | \
sort -du > libvlc-headers.sym

exec diff -u ${srcdir}/libvlc.sym libvlc-headers.sym
