#! /bin/sh
# Plugin API consistency check for VLC
# Copyright © 2007 Rémi Denis-Courmont.

rm -f libvlc-headers.sym

cat ${srcdir}/../include/vlc_*.h ${srcdir}/control/*.h | \
sed -n -e 's/^[ ]*VLC_EXPORT[ ]*([^,]*,\([^,]*\),.*/\1/p' | \
sed -e 's/[^a-zA-Z0-9_]*//' | \
sort -fdu > libvlc-headers.sym

if ! diff -u ${srcdir}/libvlccore.sym libvlc-headers.sym; then
	echo "Mismatching symbols found!"
	exit 1
fi

# TODO: we should pass this:
#if grep -e "^_" libvlc-headers.sym; then
#	echo "Illegal symbol name (starting with underscore) found!";
#	exit 1
#fi

rm -f libvlc-headers.sym
